spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oitolabs
    username: root
    password: admin
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
